language: cpp
before_install:
  - sudo apt-get install -y openmpi-bin libopenmpi-dev
compiler:
  - clang
  - gcc
script: mkdir -p build && cd build && ../configure --enable-debug && make && make test
